name: CICD

on:
  workflow_dispatch:

jobs:
  code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        run: echo "Code cloned from GitHub"

  build:
    needs: code
    runs-on: ubuntu-latest
    steps:
      - name: Build Docker container
        run: echo "Docker container build"

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Test the container
        run: echo "Testing the container"

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Deploy the app
        run: echo "Docker Compose deployed the app"
