name: portfoilo
on:
    push:
        branches: [main]
    
permissions:
        pages: write
        id-token: write        

jobs:
    deploy:
        runs-on: ubuntu-latest

        environment:
               name: github-pages
               url: ${{ steps.deployment.outputs.page_url }}

        steps:
                #get access to your protfolio code via pre-built actions

                - name: checkout code
                  uses: actions/checkout@v4

                #setup Github pages
                - name: Setup the GitHub Pages
                  uses: actions/configure-pages@v4

                #static code artifacts
                - name: upload static files
                  uses: actions/upload-pages-artifact@v4 
                  with:
                    path: "."
                  
                - name: deploy to Github pages
                  uses: actions/deploy-pages@v4
